15.0 upgrade jimm
PatrickLepere/Gudis pull request #21
Opened 2023-03-01 19:00 UTC by jimm-odoo

Mindesa upgrade from 12.0 -> 15.0

2023-03-01 19:27 UTC, kga-odoo requested changes

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/data/actions.xml
> +purchases = env['purchase.order'].search([]).filtered(lambda purchase: purchase.partner_id.is_rfq_confirm == True and purchase.user_id.is_rfq_confirm == True)
This is not suggested.
Update domain with the states required on
https://github.com/PatrickLepere/Gudis/pull/21/files#diff-c6ef0842c498d102134adcaecdc1b652d649d272ab00b2ac6dd19a29732d228dL21
Also instead of using filtered after searching.
First search partner and users where is_rfq_confirm is set.
Then update the domain for purchase order to include those partner and users.
This will make the cron lightweight and improve performance.

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/data/record_rules.xml
> +            <field name="domain_force">[('name', '=', False)]</field>
What is the purpose of this domain?

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/data/record_rules.xml
> +            <field name="domain_force">[('name', '=', False)]</field>
What is the purpose of this domain?

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/data/record_rules.xml
> +            <field name="domain_force">[('name', '=', False)]</field>
What is the purpose of this domain?

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/models/product.py
> +    product_uom = fields.Many2one('uom.uom', string='Unit of Measure (Vendor)', store=True, readonly=False, related=False, required=False)
why remove ondelete constraint?

2023-03-01 19:27 UTC, kga-odoo commented on mindesa_purchase/models/purchase_order.py
>              cr.commit()
remove all checks on line 18 after filters and domains changed in the cron itself

2023-03-02 23:04 UTC, jimm-odoo commented on mindesa_purchase/models/product.py
> +    product_uom = fields.Many2one('uom.uom', string='Unit of Measure (Vendor)', store=True, readonly=False, related=False, required=False)
There was an error with required=True and the ondelete but I'll change it to be restricted

2023-03-03 00:31 UTC, kga-odoo requested changes

2023-03-03 00:31 UTC, kga-odoo commented on mindesa_purchase/models/purchase_order.py
> +            if purchase.state in ['draft','sent']:
include this as a domain in cron itself here.
https://github.com/PatrickLepere/Gudis/pull/21/files#diff-f8f571944aca589c796913742af0c99264548c36e58f11f801ae0cf5b807af76R14
This if condition block is not needed at all in that case.

2023-03-03 00:31 UTC, kga-odoo commented on mindesa_purchase/models/purchase_order.py
> +            if purchase.state in ['draft','sent']:
### ###

2023-03-06 17:45 UTC, kga-odoo approved these changes
Approved to be merged after removing empty record rules.

2023-04-05 22:44 UTC, merged